version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - default

networks:
  default: