version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - default

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.yml
    volumes:
      - ./docs:/swagger
    networks:
      - default

networks:
  default: